language: python

env:
  - PYTHON=2.7 PANDAS=0.17.0 SKLEARN=0.16.1
  - PYTHON=2.7 PANDAS=0.18.0 SKLEARN=0.17.1
  - PYTHON=3.4 PANDAS=0.16.0 SKLEARN=0.16.1
  - PYTHON=3.4 PANDAS=0.17.0 SKLEARN=0.17.1
  - PYTHON=3.5 PANDAS=0.18.0 SKLEARN=0.17.1

addons:
  apt:
    packages:
    - graphviz

install:
  - bash scripts/build_travis.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate myenv
  - python -m nose --with-coverage --cover-package=pandas_ml
  - flake8 --ignore E501 pandas_ml

after_success:
  - coveralls
